version: '3.1'
services:

  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 8080:80

  backend:
    container_name: backend
    restart: unless-stopped
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django -d django" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
