# Generated by Django 4.0.1 on 2022-01-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('gravity', models.CharField(max_length=70)),
                ('climate', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.planet')),
            ],
        ),
    ]
